#add user conf to a brand new tomcat
FROM tomcat:9.0-jre8
MAINTAINER Eric "ewang30@its.jnj.com"

#add env
ENV DIRPATH /usr/local/tomcat

#add work dir for users
WORKDIR $DIRPATH/conf

#add manager-gui to tomcat
RUN sed -i '$s|^|<role rolename=\"manager-gui\"/>\n<user username=\"lfstomcat\" password=\"c0nn3ct\" roles=\"manager-gui\"/>\n|g' tomcat-users.xml

#change work dir to manager page
WORKDIR ../webapps/manager/META-INF

#add comments
RUN sed -i 's|<Valve|<!--<Valve|g' context.xml && sed -i 's|\:1\" />|\:1\" />-->|g' context.xml